#:package Spectre.Console@0.50.*

// Generates the precomputed rainbow figlet markup for the app header.
// Usage:
//   dotnet run tools/generate-header.cs                          # default text
//   dotnet run tools/generate-header.cs "My Custom Header"       # custom text
//
// To update the header, run this and redirect output:
//   dotnet run tools/generate-header.cs > src/NewsletterGenerator/NewsletterApp.HeaderMarkup.cs

using System.Text;
using Spectre.Console;

var text = args.Length > 0 ? args[0] : "Newsletter Generator";
var fontPath = Path.Combine("src", "NewsletterGenerator", "Assets", "ansi-shadow.flf");

if (!File.Exists(fontPath))
{
    Console.Error.WriteLine($"Font file not found: {fontPath}");
    Console.Error.WriteLine("Run this from the repository root.");
    return 1;
}

var font = FigletFont.Load(fontPath);
var banner = new FigletText(font, text)
{
    Justification = Justify.Left,
    Pad = false
};

using var writer = new StringWriter();
var console = AnsiConsole.Create(new AnsiConsoleSettings
{
    Ansi = AnsiSupport.No,
    ColorSystem = ColorSystemSupport.NoColors,
    Out = new AnsiConsoleOutput(writer),
    Interactive = InteractionSupport.No
});
// Wide enough for each word but not both, so FigletText wraps between words.
console.Profile.Width = 100;
console.Write(banner);
var plainText = writer.ToString().TrimEnd();

var rainbowAnsi = ApplyRainbowAnsi(plainText);

Console.WriteLine("namespace NewsletterGenerator;");
Console.WriteLine();
Console.WriteLine($"// Precomputed figlet \"{text}\" in ansi-shadow font with raw ANSI escape sequences.");
Console.WriteLine("// Generated by tools/generate-header.cs — regenerate if the heading text changes.");
Console.WriteLine("internal static partial class NewsletterApp");
Console.WriteLine("{");
Console.WriteLine("    private const string HeaderAnsi =");
Console.WriteLine("        \"\"\"");
foreach (var line in rainbowAnsi.Split('\n'))
{
    Console.Write("        ");
    Console.WriteLine(line);
}
Console.WriteLine("        \"\"\";");
Console.WriteLine("}");

return 0;

static string ApplyRainbowAnsi(string text, double frequency = 0.35, int spread = 7, int seed = 42)
{
    var sb = new StringBuilder();
    var lines = text.ReplaceLineEndings("\n").Split('\n');

    for (int lineNum = 0; lineNum < lines.Length; lineNum++)
    {
        int charIdx = 0;
        foreach (char c in lines[lineNum])
        {
            if (char.IsWhiteSpace(c))
            {
                sb.Append(c);
            }
            else
            {
                double phase = frequency * (seed + (double)lineNum / spread + (double)charIdx / spread);
                byte r = (byte)(Math.Sin(phase) * 127 + 128);
                byte g = (byte)(Math.Sin(phase + 2 * Math.PI / 3) * 127 + 128);
                byte b = (byte)(Math.Sin(phase + 4 * Math.PI / 3) * 127 + 128);
                sb.Append($"\x1b[38;2;{r};{g};{b}m{c}\x1b[0m");
            }
            charIdx++;
        }
        if (lineNum < lines.Length - 1)
            sb.Append('\n');
    }

    return sb.ToString();
}
